version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/oracle
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: root
